//
//  StoriesView.swift
//  VoicesAI
//
//  Created by MacBook Pro on 24/04/24.
//

import SwiftUI

struct StoriesView: View {
    
    @State private var selectedTopic: Topics = .persahabatan
    @State private var selectedMood: Mood = .bahagia
    @State private var todayStory: String = ""
    
    var body: some View {
        NavigationStack {
            Form {
                
                // MARK: - PICKER VIEW

                Section {
                    
                    Picker(selection: $selectedTopic) {
                        ForEach(Topics.allCases, id: \.self) { topic in
                            Text(topic.rawValue.capitalized)
                                .font(.subheadline)
                                .tag(topic)
                        }
                    } label: {
                        Text("Choose Topics")
                            .foregroundStyle(.gray)
                    }
                    
                    Picker(selection: $selectedMood) {
                        ForEach(Mood.allCases, id: \.self) { mood in
                            Text(mood.rawValue.capitalized)
                                .font(.subheadline)
                        }
                    } label: {
                        Text("Choose Topics")
                            .foregroundStyle(.gray)
                    }

                } header: {
                    Text("Topics")
                } footer: {
                    Text("Choose any topics and mood that you want to listen.")
                }
                
                // MARK: - TEXT EDITOR

                
                Section {
                    
                    TextEditor(text: $todayStory)
                        .frame(height: 250)
                        .font(.system(.headline, design: .rounded))
                        .foregroundStyle(.blue)
                    
                } header: {
                    Text("Todays Story")
                } footer: {
                    Text("This stories are generated by Gemini AI.")
                }
                
                Button {
                    
                } label: {
                    Text("Generate Story".uppercased())
                        .font(.system(.callout, design: .rounded))
                        .fontWeight(.bold)
                }
                .frame(minWidth: 0, maxWidth: .infinity)
                
            }
            .navigationTitle("Stories")
            .tint(.black)
        }
    }
}

#Preview {
    StoriesView()
}
