//
//  StoriesView.swift
//  VoicesAI
//
//  Created by MacBook Pro on 24/04/24.
//

import SwiftUI

struct StoriesView: View {
    
    @StateObject private var storyVM = StoryVM()
    
    @State private var selectedTopic: Topics = .persahabatan
    @State private var selectedMood: Mood = .bahagia
    
    var body: some View {
        NavigationStack {
            Form {
                
                // MARK: - PICKER VIEW

                Section {
                    
                    Picker(selection: $selectedTopic) {
                        ForEach(Topics.allCases, id: \.self) { topic in
                            Text(topic.rawValue.capitalized)
                                .font(.subheadline)
                                .tag(topic)
                        }
                    } label: {
                        Text("Choose Topics")
                            .foregroundStyle(.gray)
                    }
                    
                    Picker(selection: $selectedMood) {
                        ForEach(Mood.allCases, id: \.self) { mood in
                            Text(mood.rawValue.capitalized)
                                .font(.subheadline)
                                .tag(mood)
                        }
                    } label: {
                        Text("Choose Topics")
                            .foregroundStyle(.gray)
                    }

                } header: {
                    Text("Topics")
                } footer: {
                    Text("Choose any topics and mood that you want to listen.")
                }
                
                // MARK: - TEXT EDITOR

                Section {
                    
                    TextEditor(text: $storyVM.storyText)
                        .frame(height: 200)
                        .font(.system(.headline, design: .rounded))
                        .foregroundStyle(.blue)
                        .disabled(storyVM.isLoading)
                        .overlay {
                            storyVM.isLoading ? ProgressView() : nil
                        }
                    
                } header: {
                    Text("Todays Story")
                } footer: {
                    Text("This stories are generated by Gemini AI.")
                }
                
                Button{
                    Task {
                        await storyVM.generateStory(topic: selectedTopic, mood: selectedMood)
                    }
                } label: {
                    if storyVM.isLoading {
                        ProgressView().scaleEffect(1)
                    } else {
                        Text(storyVM.storyText.isEmpty ? "Generate".uppercased() : "Speech".uppercased())
                            .font(.system(.callout, design: .rounded))
                            .fontWeight(.bold)
                    }
                }
                .frame(minWidth: 0, maxWidth: .infinity)
                
            }
            .navigationTitle("Stories")
            .tint(.black)
        }
    }
}

#Preview {
    StoriesView()
}


